// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Patient struct {
	ID        int32          `db:"id" json:"id"`
	FullName  string         `db:"full_name" json:"full_name"`
	Age       int32          `db:"age" json:"age"`
	Gender    string         `db:"gender" json:"gender"`
	Address   sql.NullString `db:"address" json:"address"`
	Phone     sql.NullString `db:"phone" json:"phone"`
	Status    string         `db:"status" json:"status"`
	CreatedBy sql.NullInt32  `db:"created_by" json:"created_by"`
	CreatedAt sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        int32        `db:"id" json:"id"`
	Username  string       `db:"username" json:"username"`
	Password  string       `db:"password" json:"password"`
	Role      string       `db:"role" json:"role"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}
